# Generated by Django 2.2.5 on 2019-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('mobile_number', models.IntegerField(max_length=11)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
